services:
  web:
    build:
      context: ./pwa
      dockerfile: Dockerfile
    container_name: pwa_study
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: ./pwa/src
        target: /app
